In [1]:
print("Hello World")

Hello World


<h1 style="text-align: center;">Python Variables</h1>

In [2]:
student = "Lokendra Bdr. Bhat"

In [3]:
student

'Lokendra Bdr. Bhat'

In [4]:
student="Bhat Jee"

In [5]:
student

'Bhat Jee'

In [6]:
student="Khadak Bhat"

In [7]:
student

'Khadak Bhat'

<h1 style="text-align: center;">Python DataTypes</h1>

In [8]:
a1 = 25
a1


25

In [9]:
type(a1)

int

In [10]:
a1 = 25.548
a1

25.548

In [11]:
type(a1)

float

In [12]:
a1 = True
a1

True

In [13]:
type(a1)

bool

In [14]:
a1 = "Lokendra Bhat"
a1

'Lokendra Bhat'

In [15]:
type(a1)

str

In [16]:
a1 = 25+5J
a1

(25+5j)

In [17]:
type(a1)

complex

<h1 style="text-align: center;">Operators in Python</h1>

<h4 style="text-align:center;">Arithmetic Operators</h4>

In [18]:
#+, -, *, /

In [19]:
a=20
b=5

In [20]:
a,b

(20, 5)

In [21]:
a+b

25

In [22]:
a-b

15

In [23]:
a*b

100

In [24]:
a/b

4.0

<h4 style="text-align:center;">Relational Operators</h4>

In [25]:
#>, <, ==, >=, <=, !=

In [26]:
a = 50
b = 75

In [27]:
a>b

False

In [28]:
a<b

True

In [29]:
a==b

False

In [30]:
a!=b

True

<h4 style="text-align:center;">Logical Operators</h4>

In [31]:
# &, |

In [32]:
a = True
b = False

In [33]:
a & a

True

In [34]:
a & b

False

In [35]:
b & b

False

In [36]:
a!=b

True

In [37]:
b&a

False

In [38]:
a|b

True

In [39]:
b|a

True

In [40]:
b|b

False

In [41]:
a|a

True

<h1 style="text-align: center;">Python Tokens</h1>

<h4 style="text-align: center;">Python Keywords</h4>

In [42]:
#False, def, from, or

<h4 style="text-align: center;">Python Identifiers</h4>

In [43]:
d="Loken"

In [44]:
D="Bhat"

In [45]:
d

'Loken'

In [46]:
D

'Bhat'

<h4 style="text-align: center;">Python Literals</h4>

In [47]:
a="Hello Bhat Jee"

In [48]:
b=3.45

<h1 style="text-align: center;">Python Strings</h1>

In [49]:
so='This is the single quotes string'

In [50]:
so

'This is the single quotes string'

In [51]:
si = "This is the Double quotes string"

In [52]:
si

'This is the Double quotes string'

In [53]:
str='''
This string
has
lot of lines
like it
'''

In [54]:
str

'\nThis string\nhas\nlot of lines\nlike it\n'

<h1 style="text-align: center;">Extracting Individual Characters As Indexing</h1>

In [55]:
my_string="My name is Bhat Lok"#select fist character

In [56]:
my_string[0]

'M'

In [57]:
my_string = "My name is Bhat lok" #select last characters

In [58]:
my_string[-1]

'k'

In [59]:
my_string[5:15]

'me is Bhat'

<h1 style="text-align: center;">String Functions in Python</h1>

In [60]:
por="My name is Lokendra Bhat"
por

'My name is Lokendra Bhat'

In [61]:
len(por)

24

In [62]:
por.lower()

'my name is lokendra bhat'

In [63]:
por.upper()

'MY NAME IS LOKENDRA BHAT'

In [64]:
por.replace('is','are')

'My name are Lokendra Bhat'

In [65]:
strs='Hello Hello Bhat Bhat 200 00 200'

In [66]:
strs.count("Hello")

2

In [67]:
strs.count("00")

3

In [68]:
my_string = "Hello world to welcome"

In [69]:
my_string.find('to')

12

In [70]:
my_string.find('we')

15

In [71]:
str_l="President Obama is the best president of United State"
str_l

'President Obama is the best president of United State'

In [72]:
str_l.split('e')

['Pr',
 'sid',
 'nt Obama is th',
 ' b',
 'st pr',
 'sid',
 'nt of Unit',
 'd Stat',
 '']

<h1 style="text-align: center;">Data Structures in Python</h1>

<h4 style="text-align: center;">Data Tuple in Python</h1>

In [73]:
tupl=(1,True, 3.54,6+4j,'Lokendra',5)

In [74]:
tupl

(1, True, 3.54, (6+4j), 'Lokendra', 5)

In [75]:
type(tupl)

tuple

In [76]:
tupl[0]

1

In [77]:
tupl[-1]

5

In [78]:
tupl[2:5]

(3.54, (6+4j), 'Lokendra')

<h1 style="text-align: center;">Tuple Basic Operations in Python</h1>

<h3 style="text-align: center;">Finding Length of Tuple in Python</h1>

In [79]:
tupls=(2,"apple", True, "Banana", 8, 80.54, 4+5J)

In [80]:
tupls

(2, 'apple', True, 'Banana', 8, 80.54, (4+5j))

In [81]:
len(tupls)

7

<h4 style="text-align: center;">Concatenating Tuples in Python</h4>

In [82]:
tupls1=(2,4,6,8)
tupls2=(1,3,5,7,9)
tupls1+tupls2

(2, 4, 6, 8, 1, 3, 5, 7, 9)

<h4 style="text-align: center;">Repeating Tuples in Python</h1>

In [83]:
tupl=("Lokendra", "Bhat",900)

In [84]:
tupl*3

('Lokendra', 'Bhat', 900, 'Lokendra', 'Bhat', 900, 'Lokendra', 'Bhat', 900)

<h4 style="text-align: center;">Repeating and Concatenating in Python</h1>

In [85]:
tup1=('Lokendra',45)
tup2=('Bhat',8,9)
tup1*7+tup2

('Lokendra',
 45,
 'Lokendra',
 45,
 'Lokendra',
 45,
 'Lokendra',
 45,
 'Lokendra',
 45,
 'Lokendra',
 45,
 'Lokendra',
 45,
 'Bhat',
 8,
 9)

<h3 style="text-align: center;">Tuple Functions in Python</h3>

<h5 style="text-align: center;">Minimum Value in Python</h5>

In [86]:
tup1=(45,6,8,9,10)
min(tup1)

6

<h5 style="text-align: center;">Maximum Value in Python</h5>

In [87]:
max(tup1)

45

<h1 style="text-align: center;">Lists in Python</h1>

In [88]:
list1=[1,'Lokendra', 67, 9,True,'paa']

In [89]:
list1

[1, 'Lokendra', 67, 9, True, 'paa']

In [90]:
type(list1)

list

In [91]:
list1[0]

1

In [92]:
list1[-1]

'paa'

In [93]:
list1[1:6]

['Lokendra', 67, 9, True, 'paa']

In [94]:
list1=[1,'a', 2, 'b', 3, 'c', 4, 'd']

<h2 style="text-align: center;">Modify A List in Python</h2>

In [95]:
list1

[1, 'a', 2, 'b', 3, 'c', 4, 'd']

In [96]:
list1[0]=20 #Add new data in the 0th place

In [97]:
list1

[20, 'a', 2, 'b', 3, 'c', 4, 'd']

In [98]:
list1.pop() #Remove Data from exist data from last element

'd'

In [99]:
list1

[20, 'a', 2, 'b', 3, 'c', 4]

In [100]:
list1.append('Lokendra') #Appending a new elements

In [101]:
list1

[20, 'a', 2, 'b', 3, 'c', 4, 'Lokendra']

In [102]:
list1.reverse() # Reversing Elements of a list

In [103]:
list1

['Lokendra', 4, 'c', 3, 'b', 2, 'a', 20]

In [104]:
list1.insert(3,'Bhat') #insert data at index-3

In [105]:
list1

['Lokendra', 4, 'c', 'Bhat', 3, 'b', 2, 'a', 20]

In [106]:
list1=[4,8,2,7,9,12,5,1,3]

In [107]:
list1.sort() #Sort the data

In [108]:
list1

[1, 2, 3, 4, 5, 7, 8, 9, 12]

<h2 style="text-align: center;">List Basic Operations in Python</h2>

In [109]:
l1=[1,2,3,4]
l2=['a', 'b', 'c','d']
l1+l2        #Concatenating elements

[1, 2, 3, 4, 'a', 'b', 'c', 'd']

In [110]:
l1=['a', 100, 'y', True]

In [111]:
l1*3

['a', 100, 'y', True, 'a', 100, 'y', True, 'a', 100, 'y', True]

In [112]:
l1*4+l2

['a',
 100,
 'y',
 True,
 'a',
 100,
 'y',
 True,
 'a',
 100,
 'y',
 True,
 'a',
 100,
 'y',
 True,
 'a',
 'b',
 'c',
 'd']

<h1 style="text-align: center;">Dictionary in Python</h1>

In [113]:
dic1={"Banana":90,"Mango":120,"Apple":60}

In [114]:
dic1

{'Banana': 90, 'Mango': 120, 'Apple': 60}

In [115]:
type(dic1)

dict

In [116]:
dic1.keys() #Extracting Keys

dict_keys(['Banana', 'Mango', 'Apple'])

In [117]:
dic1.values() #Extracting Values

dict_values([90, 120, 60])

<h3 style="text-align: center;">Modify a Dictionary in Python</h3>

In [118]:
dic2={"Banana":50, "Mango":100, "Apple":150, "Orange":200, "Sugar":250}
dic2["Guava"]=300 #Adding a new elemets
dic2

{'Banana': 50,
 'Mango': 100,
 'Apple': 150,
 'Orange': 200,
 'Sugar': 250,
 'Guava': 300}

In [119]:
dic2["Banana"]=350 #Changing an Existing elements

In [120]:
dic2

{'Banana': 350,
 'Mango': 100,
 'Apple': 150,
 'Orange': 200,
 'Sugar': 250,
 'Guava': 300}

<h3 style="text-align: center;">Dictionary Functions in Python</h3>

In [121]:
d1={"Apple":100, "Banana":150,"Mango":200, "Orange":250,"Grapes":300}
d2={"Papaya":400, "Jack-fruit":450}

In [122]:
d1.update(d2)

In [123]:
d1

{'Apple': 100,
 'Banana': 150,
 'Mango': 200,
 'Orange': 250,
 'Grapes': 300,
 'Papaya': 400,
 'Jack-fruit': 450}

In [124]:
d1.pop("Grapes")

300

In [125]:
d1

{'Apple': 100,
 'Banana': 150,
 'Mango': 200,
 'Orange': 250,
 'Papaya': 400,
 'Jack-fruit': 450}

<h1 style="text-align: center;">Set in Python</h1>

In [126]:
set1={1,'a','b',2,True,False}

In [127]:
set1

{1, 2, False, 'a', 'b'}

<h3 style="text-align: center;">Set Operations in Python</h3>

In [128]:
set1={1,'a','b',2,True,False}
set1

{1, 2, False, 'a', 'b'}

In [129]:
set1.add("Lokendra")

In [130]:
set1

{1, 2, False, 'Lokendra', 'a', 'b'}

In [131]:
set1.update(["Bhat",4587937,8+9j])

In [132]:
set1

{(8+9j), 1, 2, 4587937, 'Bhat', False, 'Lokendra', 'a', 'b'}

In [133]:
set1.remove(False)

In [134]:
set1

{(8+9j), 1, 2, 4587937, 'Bhat', 'Lokendra', 'a', 'b'}

In [135]:
set1.remove("Bhat")

In [136]:
set1

{(8+9j), 1, 2, 4587937, 'Lokendra', 'a', 'b'}

<h3 style="text-align: center;">Set Functions in Python</h3>

In [137]:
s1={5,6,7,8,9,13}
s2={5, 'a', 8, 'b', 'c', 'd'}

In [138]:
s1.union(s2)

{13, 5, 6, 7, 8, 9, 'a', 'b', 'c', 'd'}

In [139]:
s1.intersection(s2)

{5, 8}

<h1 style="text-align: center;">IF Statements in Python</h>

In [140]:
a=20

In [141]:
b=52

In [142]:
if a<b:
    print('B is greater than A')

B is greater than A


In [143]:
if a>b:
    print('A is greater than B')

In [144]:
if b>a:
    print("B is Greater than A")
else:
    print("A is grater than B")

B is Greater than A


In [145]:
a=7
b=10
c=15
if (a>b) & (a>c):
    print("A is the greater")
elif (b>a)&(b>c):
    print("B is the Greater")
else:
    print("C is the Greate")

C is the Greate


<h3 style="text-align: center;">IF Statements with tuple in Python</h3>

In [146]:
tupl=('a', 'b', 'c', 'd')

In [147]:
if 'a' in tupl:
    print("Value a is present in tupl")

Value a is present in tupl


In [148]:
if 'z' in tupl:
    print("Value z is present in tupl")
else:
    print("Value a is present in tupl")

Value a is present in tupl


<h3 style="text-align: center;">IF Statements with List in Python</h3>

In [149]:
lis=['a','b','c']

In [150]:
if lis[1]=='b':
    lis[1]='z'

In [151]:
lis

['a', 'z', 'c']

<h3 style="text-align: center;">IF Statements with Dictionary's in Python</h3>

In [152]:
dic1={'appale':100,'Banana':350,'Mango':500}

In [153]:
if dic1['Banana']==350:
    dic1['Banana'] = dic1['Banana']+450

In [154]:
dic1

{'appale': 100, 'Banana': 800, 'Mango': 500}

<h1 style="text-align: center;">Looping Statements in Python</h1>

<h3 style="text-align: center;">While Loop in Python</h3>

In [155]:
i=1
while i<=10:
    print(i)
    i=i+1

1
2
3
4
5
6
7
8
9
10


In [156]:
a=1
n=2
while a<=10:
    print(n, " * ", a, " = ", n*a)
    a=a+1

2  *  1  =  2
2  *  2  =  4
2  *  3  =  6
2  *  4  =  8
2  *  5  =  10
2  *  6  =  12
2  *  7  =  14
2  *  8  =  16
2  *  9  =  18
2  *  10  =  20


In [157]:
i=1
n=3
while i<=10:
    print(n, " * ", i, " = ", n*i)
    i=i+1

3  *  1  =  3
3  *  2  =  6
3  *  3  =  9
3  *  4  =  12
3  *  5  =  15
3  *  6  =  18
3  *  7  =  21
3  *  8  =  24
3  *  9  =  27
3  *  10  =  30


In [158]:
i=1
n=4
while i<=10:
    print(n, " * ", i, " = ", n*i)
    i=i+1

4  *  1  =  4
4  *  2  =  8
4  *  3  =  12
4  *  4  =  16
4  *  5  =  20
4  *  6  =  24
4  *  7  =  28
4  *  8  =  32
4  *  9  =  36
4  *  10  =  40


<h3 style="text-align: center;">While Loop with List in Python</h3>

In [159]:
l1=[1,2,3,4,5]

In [160]:
i=0
while i<len(l1):
    l1[i]=l1[i]+100
    i=i+1

In [161]:
l1

[101, 102, 103, 104, 105]

<h3 style="text-align: center;">For Loop in Python</h3>

In [162]:
li=['mango', 'Banana', 'Orange', 'Grapes','Apple']

In [163]:
for i in li:
    print(i)


mango
Banana
Orange
Grapes
Apple


In [164]:
l1 = ['Orange','Black', 'White','Red']
l2=['Chair','Book','Laptop','Mobile']

In [165]:
for i in l1:
    for j in l2:
        print(i,j)

Orange Chair
Orange Book
Orange Laptop
Orange Mobile
Black Chair
Black Book
Black Laptop
Black Mobile
White Chair
White Book
White Laptop
White Mobile
Red Chair
Red Book
Red Laptop
Red Mobile


<h1 style="text-align: center;">Functions in Python</h1>

In [166]:
def hellof():
    print('Hello World!')

In [167]:
hellof()

Hello World!


In [168]:
def add_10(x):
    return x+10

In [169]:
add_10(40)

50

In [170]:
def odd_even(x):
    if x%2==0:
        print(x, ' is Even')
    else:
        print(x, ' is Odd')

In [171]:
odd_even(6)

6  is Even


In [172]:
odd_even(5)

5  is Odd


In [173]:
g = lambda x: x*x*x

In [174]:
g(8)

512

In [175]:
g(2)

8

In [176]:
g(10)

1000

<h3 style="text-align: center;">Lambda with Filter in Python</h3>

In [177]:
l1 = [1,5,6,7,8,45,89,4,15,9]

In [178]:
final_list=list(filter(lambda x:(x%2!=0),l1))

In [179]:
final_list

[1, 5, 7, 45, 89, 15, 9]

In [180]:
final_list=list(filter(lambda x:(x%2==0),l1))

In [181]:
final_list

[6, 8, 4]

<h3 style="text-align: center;">Lambda with map in Python</h3>

In [182]:
l1 = [45,8,10,12,14,20,16]

In [183]:
list_final_new=list(map(lambda x:x*2,l1))

In [184]:
list_final_new

[90, 16, 20, 24, 28, 40, 32]

<h3 style="text-align: center;">Lambda with Reduce in Python</h3>

In [185]:
from functools import reduce

In [186]:
sum=reduce(lambda x,y:x+y,l1)

In [187]:
sum

125

 <h1 style="text-align: center;">Class in Python</h1>

In [188]:
class Phone:
    def make_Call(self):
        print("I am Making a Call")
    def play_game(self):
        print("I am Playing a game")

In [189]:
p1 = Phone()

In [190]:
p1.make_Call()

I am Making a Call


In [191]:
p1.play_game()

I am Playing a game


<h3 style="text-align: center;">Adding Parameters to the class in Python</h3>

In [192]:
class Phone:
    def set_color(self, color):
        self.color=color
    def set_cost(self, cost):
        self.cost = cost
    def show_color(self):
        return self.color
    def show_cost(self):
        return self.cost
    def make_call(self):
        print("Make a call")
    def play_game(self):
        print("Play a Game")

In [193]:
p2 = Phone()

In [194]:
p2.set_color('Blue')

In [195]:
p2.set_cost(5000)

In [196]:
p2.show_color()

'Blue'

In [197]:
p2.show_cost()

5000

In [198]:
p2.make_call()

Make a call


In [199]:
p2.play_game()

Play a Game


<h3 style="text-align: center;">Creating a class with Constructor in Python</h3>

In [200]:
class Employee:
    def __init__(self, name, age, salary, gender):
        self.name = name
        self.age = age
        self.salary = salary
        self.gender = gender
    def employee_details(self):
        print("Name of Employee ", self.name)
        print("Age of Employee ", self.age)
        print("Salary of Employee ", self.salary)
        print("Gender of Employee ", self.gender)

In [201]:
E1= Employee("Lokendra Bhat", 25, 95780, "Male")

In [202]:
E1.employee_details()

Name of Employee  Lokendra Bhat
Age of Employee  25
Salary of Employee  95780
Gender of Employee  Male


<h1 style="text-align: center;">Creating a class with Inheritance in Python</h1>

In [203]:
class Vehicle:
    def __init__(self, mileage, cost):
        self.mileage = mileage
        self.cost = cost
    
    def show_vehicle_details(self):
        print("Mileage of Vehicle is", self.mileage)
        print("Cost of Vehicle is", self.cost)
        print("I am a Vehicle")

In [204]:
V1 = Vehicle(5000, 45000)

In [205]:
V1.show_vehicle_details()

Mileage of Vehicle is 5000
Cost of Vehicle is 45000
I am a Vehicle


<h3 style="text-align: center;">Creating a child class with Inheritance in Python</h3>

In [206]:
class Car(Vehicle):
    def show_car_details(self):
        print("I am a Car")

In [207]:
c1 = Car(300,900)

In [208]:
c1.show_vehicle_details()

Mileage of Vehicle is 300
Cost of Vehicle is 900
I am a Vehicle


In [209]:
c1.show_car_details()

I am a Car


<h3 style="text-align: center;">Over-riding init Method in Python</h3>

In [210]:
class Car(Vehicle):
    def __init__(self,mileage,cost,tyres,hp):
        super().__init__(mileage,cost)
        self.tyres = tyres
        self.hp = hp
    def show_car_details(self):
        print("Number of tyres in car: ", self.tyres)
        print("Horse power of car is ", self.hp)
        print("I am a Car")

In [211]:
c1 = Car(45,450000,8,789000)

In [212]:
c1.show_car_details()

Number of tyres in car:  8
Horse power of car is  789000
I am a Car


In [213]:
c1.show_vehicle_details()

Mileage of Vehicle is 45
Cost of Vehicle is 450000
I am a Vehicle


<h1 style="text-align: center;">Multiple Inheritance in Python</h1>

In [214]:
class Parent1:
    def assign_string_one(self,str1):
        self.str1 = str1
    def show_string_one(self):
        return self.str1

In [215]:
class Parent2:
    def assign_string_two(self,str2):
        self.str2 = str2
    def show_string_two(self):
        return self.str2

In [216]:
class Child(Parent1, Parent2):
    def assign_string_three(self,str3):
        self.str3 = str3
    def show_string_three(self):
        return self.str3

In [217]:
my_child=Child()

In [218]:
my_child.assign_string_one("I am string of Parent 1")

In [219]:
my_child.assign_string_two("I am string of Parent 2")

In [220]:
my_child.assign_string_three("I am string of Child")

In [221]:
my_child.show_string_one()

'I am string of Parent 1'

In [222]:
my_child.show_string_two()

'I am string of Parent 2'

In [223]:
my_child.show_string_three()

'I am string of Child'

<h1 style="text-align: center;">Multi-level Inheritance in Python</h1>

In [224]:
class Parent:
    def get_name(self,name):
        self.name = name
    def show_name(self):
        return self.name

In [225]:
class Child(Parent):
    def get_age(self, age):
        self.age = age
    def show_age(self):
        return self.age

In [226]:
class GrandChild(Child):
    def get_gender(self,gender):
        self.gender = gender
    def show_gender(self):
        return self.gender

In [227]:
my_gender = GrandChild()

In [228]:
my_gender.get_name("Lokendra")

In [229]:
my_gender.get_age(45)

In [230]:
my_gender.get_gender("Male")

In [231]:
my_gender.show_name()

'Lokendra'

In [232]:
my_gender.show_age()

45

In [233]:
my_gender.show_gender()

'Male'

<h1 style="text-align:center" > Librareis in Python </h1>

<h3 style="text-align:center" > NumPy Librareis in Python </h3>

<h4 style="text-align:center" >Single-diamensional Array in Python </h4>

In [234]:
import numpy as np

In [235]:
l1=[20,30,10,50]

In [236]:

n1=np.array(l1)
n1

array([20, 30, 10, 50])

In [237]:
type(n1)

numpy.ndarray

<h4 style="text-align:center" >Multi-diamensional Array in Python </h4>

In [238]:
l2=[[14,58,46,78,82],[85,41,23,30,45]]

In [239]:
n2=np.array(l2)

In [240]:
n2

array([[14, 58, 46, 78, 82],
       [85, 41, 23, 30, 45]])

<h4 style="text-align:center" >Initializing NumPy Array with Zeros in Python </h4>

In [241]:
n3=np.zeros((2,3))

In [242]:
n3

array([[0., 0., 0.],
       [0., 0., 0.]])

In [243]:
n4=np.zeros((10,10))

In [244]:
n4

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

<h4 style="text-align:center" >Initializing NumPy Array with same in Python </h4>

In [245]:
import numpy as np
n5=np.full((3,3),12)

In [246]:
n5

array([[12, 12, 12],
       [12, 12, 12],
       [12, 12, 12]])

In [247]:
n6=np.full((5,5),8)

In [248]:
n6

array([[8, 8, 8, 8, 8],
       [8, 8, 8, 8, 8],
       [8, 8, 8, 8, 8],
       [8, 8, 8, 8, 8],
       [8, 8, 8, 8, 8]])

<h4 style="text-align:center" >Initializing NumPy Array with a range in Python </h4>

In [249]:
n1 = np.arange(50,101)

In [250]:
n1

array([ 50,  51,  52,  53,  54,  55,  56,  57,  58,  59,  60,  61,  62,
        63,  64,  65,  66,  67,  68,  69,  70,  71,  72,  73,  74,  75,
        76,  77,  78,  79,  80,  81,  82,  83,  84,  85,  86,  87,  88,
        89,  90,  91,  92,  93,  94,  95,  96,  97,  98,  99, 100])

In [251]:
n1=np.arange(50,500,10)

In [252]:
n1

array([ 50,  60,  70,  80,  90, 100, 110, 120, 130, 140, 150, 160, 170,
       180, 190, 200, 210, 220, 230, 240, 250, 260, 270, 280, 290, 300,
       310, 320, 330, 340, 350, 360, 370, 380, 390, 400, 410, 420, 430,
       440, 450, 460, 470, 480, 490])

In [253]:
n1=np.arange(50,600,20)

In [254]:
n1

array([ 50,  70,  90, 110, 130, 150, 170, 190, 210, 230, 250, 270, 290,
       310, 330, 350, 370, 390, 410, 430, 450, 470, 490, 510, 530, 550,
       570, 590])

<h4 style="text-align:center" >Initializing NumPy Array with random numbers in Python </h4>

In [255]:
n1 = np.random.randint(1,100,10)

In [256]:
n1

array([84, 30, 54, 81, 39, 90, 85, 78, 87, 50], dtype=int32)

<h4 style="text-align:center;">NumPy-Shape in Python</h4>

In [257]:
import numpy as np

In [258]:
n1 = np.array([[12,5,8,9,10],[4,6,78,90,15]])

In [259]:
n1

array([[12,  5,  8,  9, 10],
       [ 4,  6, 78, 90, 15]])

In [260]:
n1.shape = (5,2)

In [261]:
n1

array([[12,  5],
       [ 8,  9],
       [10,  4],
       [ 6, 78],
       [90, 15]])

In [262]:
n1.shape = (2,5)

In [263]:
n1

array([[12,  5,  8,  9, 10],
       [ 4,  6, 78, 90, 15]])

In [264]:
n1.shape = (1,10)

In [265]:
n1

array([[12,  5,  8,  9, 10,  4,  6, 78, 90, 15]])

In [266]:
n1.shape = (10,1)

In [267]:
n1

array([[12],
       [ 5],
       [ 8],
       [ 9],
       [10],
       [ 4],
       [ 6],
       [78],
       [90],
       [15]])

<h4 style="text-align:center;">Joinin NumPy Arrays in Python</h4>

In [268]:
n1 = np.array([1,2,3])

In [269]:
n2=np.array([4,5,6])

In [270]:
np.vstack((n1,n2))

array([[1, 2, 3],
       [4, 5, 6]])

In [271]:
np.hstack((n1,n2))

array([1, 2, 3, 4, 5, 6])

In [272]:
np.column_stack((n1,n2))

array([[1, 4],
       [2, 5],
       [3, 6]])

<h4 style="text-align:center;">NumPy Intersection & Difference in Python</h4>

In [273]:
import numpy as np

In [274]:
n1 = np.array([10, 20, 30, 40, 50, 60])

In [275]:
n2 = np.array([40, 50, 60, 70, 80,90])

In [276]:
np.intersect1d(n1,n2)

array([40, 50, 60])

In [277]:
np.setdiff1d(n1,n2)

array([10, 20, 30])

In [278]:
np.setdiff1d(n2,n1)

array([70, 80, 90])

<h2 style="text-align:center;">NumPy Arrays Mathematics in Python</h2>

<h4 style="text-align:center;">Addition of NumPy Arrays in Python</h4>

In [279]:
import numpy as np

In [280]:
n1 = np.array([50,40])

In [281]:
n2 = np.array([10, 30])

In [282]:
np.sum([n1,n2])

np.int64(130)

In [283]:
np.sum([n1,n2],axis=0)

array([60, 70])

In [284]:
np.sum([n1,n2],axis=1)

array([90, 40])

<h3 style="text-align:center;">Basic Operations in Python</h3
                                                             >

<h4 style="text-align:center;">Basic Additions Arrays in Python</h4>

In [285]:
import numpy as np

In [286]:
n1 = np.array([10, 20, 30])

In [287]:
n1 = n1 + 1
n1

array([11, 21, 31])

<h4 style="text-align:center;">Basic Subtractions Arrays in Python</h4>

In [288]:
n1 = np.array([10,20,30])

In [289]:
n1=n1-1

In [290]:
n1

array([ 9, 19, 29])

<h4 style="text-align:center;">Basic Multiplication Arrays in Python</h4>

In [291]:
n1*10

array([ 90, 190, 290])

In [292]:
n1/5

array([1.8, 3.8, 5.8])

<h4 style="text-align:center;">Mean Arrays in Python</h4>

In [293]:
import numpy as np
n1 = np.random.randint(1,100,10)

In [294]:
n1

array([80, 64, 45, 26, 52, 80, 59, 46, 43, 16], dtype=int32)

In [295]:
np.mean(n1)

np.float64(51.1)

<h4 style="text-align:center;">Standard Deviation Arrays in Python</h4>

In [296]:
np.std(n1)

np.float64(19.725364381932213)

<h4 style="text-align:center;">Median Arrays in Python</h4>

In [297]:
np.median(n1)

np.float64(49.0)

<h4 style="text-align:center;">NumPy Save & Load in Python</h4>

In [298]:
import numpy as np

In [299]:
n1 = np.array([10,20,30,40,50])
np.save('my_numpy',n1)

In [300]:
n2 = np.load('my_numpy.npy')

In [301]:
n2

array([10, 20, 30, 40, 50])